version: "3.9"

services:
  web-dev:
    container_name: document-report-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - ${UPLOADS_HOST_PATH}:/app/public/uploads
      - ${LIBRARY_HOST_PATH}:/app/public/processed_library
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    profiles: ["dev"]

  web-prod:
    container_name: document-report-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ${UPLOADS_HOST_PATH}:/app/public/uploads
      - ${LIBRARY_HOST_PATH}:/app/public/processed_library
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    profiles: ["prod"]
